// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwVhAMsUJ2jQGkMwbXGLotnd-XumqVVBs',
    appId: '1:1024928922629:web:b5a13592bacfbe693ef06c',
    messagingSenderId: '1024928922629',
    projectId: 'hospitality-crisis-bridge',
    authDomain: 'hospitality-crisis-bridge.firebaseapp.com',
    storageBucket: 'hospitality-crisis-bridge.firebasestorage.app',
    measurementId: 'G-FL375WFQYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjNLQDInTHh2v6be7xE0ZWPanogPHFxUM',
    appId: '1:1024928922629:android:4efe3a954cefe2dd3ef06c',
    messagingSenderId: '1024928922629',
    projectId: 'hospitality-crisis-bridge',
    storageBucket: 'hospitality-crisis-bridge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARv5CKxC5VUKbdqQ9aHUklb0hh9lUjENk',
    appId: '1:1024928922629:ios:8fc489c8a43ea9463ef06c',
    messagingSenderId: '1024928922629',
    projectId: 'hospitality-crisis-bridge',
    storageBucket: 'hospitality-crisis-bridge.firebasestorage.app',
    iosBundleId: 'com.example.hospitalityCrisisBridge',
  );
}
